/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32l4xx.h"
volatile uint8_t set=0;



int main(void)
{
   RCC->AHB2ENR |=RCC_AHB2ENR_GPIOCEN| RCC_AHB2ENR_GPIOEEN;

   GPIOC->MODER=(GPIOC->MODER &~GPIO_MODER_MODE6_Msk) | (1<<GPIO_MODER_MODE6_Pos);

   GPIOE->MODER =(GPIOE->MODER & ~GPIO_MODER_MODE15_Msk);

   RCC->APB2ENR|=RCC_APB2ENR_SYSCFGEN;

   SYSCFG->EXTICR[3] |= SYSCFG_EXTICR4_EXTI15_PE;

   EXTI->IMR1 |=EXTI_IMR1_IM15;

   EXTI->FTSR1 |= EXTI_FTSR1_FT15;

   NVIC_EnableIRQ(EXTI15_10_IRQn);


   while (1){

	 if(set==1){
		 for (int i=100000; i>0; i--);
		 GPIOC->ODR &= ~GPIO_ODR_OD6;
		 set=0;
	 }
}
}
//ob. ptrzewwania
void EXTI15_10_IRQHandler(void){
	if ((EXTI->PR1 & EXTI_PR1_PIF15) !=0){
		EXTI->PR1|= EXTI_PR1_PIF15;
		GPIOC->ODR |= GPIO_ODR_OD6;
		set=1;
	}
	NVIC_ClearPendingIRQ(EXTI15_10_IRQn);
}
